from .foundations import FOUNDATIONS_QUESTIONS
from .effects import EFFECTS_QUESTIONS
from .tests import TESTS_QUESTIONS
from .risk import RISK_QUESTIONS

QUESTIONS = FOUNDATIONS_QUESTIONS + EFFECTS_QUESTIONS + TESTS_QUESTIONS + RISK_QUESTIONS
