"""Questions from the provided toxicology notes."""

EFFECTS_QUESTIONS = [{'id': 'hemolytic_anemia',
  'page': 5,
  'question': 'Was kennzeichnet eine hämolytische Anämie?',
  'answers': ['Rote Blutkörperchen werden vorzeitig zerstört', 'Es wird zu viel Hämoglobin gebildet', 'Nur die Leber wird vergrößert'],
  'correct': 0,
  'explanation': 'Bei hämolytischer Anämie werden rote Blutkörperchen vorzeitig zerstört; als Beispiel nennen die Notizen Favismus bei G6PD-Mangel.',
  'variants': ['platform_gates', 'pokemon_battle']},
 {'id': 'methemoglobinemia',
  'page': 5,
  'question': 'Was ist bei einer Methämoglobinämie beeinträchtigt?',
  'answers': ['Die Sauerstoffversorgung', 'Die Knochenbildung', 'Nur die Gallensekretion'],
  'correct': 0,
  'explanation': 'Ein erhöhter Methämoglobin-Gehalt im Blut beeinträchtigt die O2-Versorgung.',
  'variants': ['lab_catcher', 'comet_click']},
 {'id': 'allergy_sensitization',
  'page': 5,
  'question': 'Was gehört laut Notizen zur Allergie?',
  'answers': ['Sensibilisierung und Antigen-Antikörper-Reaktion', 'Keine Sensibilisierung', 'Nur eine Dosis-Wirkungskurve ohne Immunreaktion'],
  'correct': 0,
  'explanation': 'Bei Allergie nennen die Notizen Sensibilisierung, Antigen-Antikörper-Reaktion und keine wichtige Dosis-Wirkungsbeziehung.',
  'variants': ['sword_arena', 'pokemon_battle']},
 {'id': 'pseudoallergy',
  'page': 5,
  'question': 'Was unterscheidet die Pseudoallergie laut Notizen von der Allergie?',
  'answers': ['Keine Sensibilisierung und keine Antigen-Antikörper-Reaktion', 'Sie ist immer genetisch', 'Sie betrifft nur die Niere'],
  'correct': 0,
  'explanation': 'Die Pseudoallergie verläuft ohne Sensibilisierung und ohne Antigen-Antikörper-Reaktion; eine Dosis-Wirkungskurve ist möglich.',
  'variants': ['platform_gates', 'comet_click']},
 {'id': 'genotoxicity_mutagenicity',
  'page': 5,
  'question': 'Welche Aussage zu Genotoxizität und Mutagenität stimmt laut Notizen?',
  'answers': ['Nicht jede genotoxische Schädigung führt zu einer Mutation', 'Genotoxizität ist immer erblich', 'Mutagenität ist immer reparierbar'],
  'correct': 0,
  'explanation': 'Genotoxische Schäden können reparierbar sein; mutagene Veränderungen sind permanent und vererbbar. Nicht jede genotoxische Schädigung führt zwangsläufig zu einer Mutation.',
  'variants': ['lab_catcher', 'sword_arena']},
 {'id': 'carcinogenesis_initiation',
  'page': 6,
  'question': 'Was kennzeichnet die Initiation der Kanzerogenese?',
  'answers': ['Irreversible DNA-Schädigung', 'Nur reversible Zellvermehrung', 'Ausscheidung des Kanzerogens'],
  'correct': 0,
  'explanation': 'Initiation ist in den Notizen als irreversible DNA-Schädigung beschrieben; eine sichere Wirkschwelle wird nicht angegeben.',
  'variants': ['comet_click', 'maze_portals']},
 {'id': 'carcinogenesis_promotion',
  'page': 6,
  'question': 'Was geschieht in der Promotion?',
  'answers': ['Vermehrung bereits initiierter Zellen', 'Erste DNA-Schädigung entsteht zwingend', 'DNA wird vollständig repariert'],
  'correct': 0,
  'explanation': 'Promotion ist die Vermehrung bereits initiierter Zellen; die Wirkung kann grundsätzlich reversibel sein.',
  'variants': ['pokemon_battle', 'lab_catcher']},
 {'id': 'carcinogenesis_progression',
  'page': 6,
  'question': 'Was beschreibt die Progression?',
  'answers': ['Krebsartige Entartung mit weiteren Veränderungen', 'Nur Resorption im Dünndarm', 'Nur reversible Rezeptorbindung'],
  'correct': 0,
  'explanation': 'In der Progression führen weitere Veränderungen zur malignen Entartung bzw. möglichen Tumorbildung.',
  'variants': ['pokemon_battle', 'comet_click']},
 {'id': 'carcinoma_sarcoma',
  'page': 6,
  'question': 'Woraus entwickelt sich ein Karzinom?',
  'answers': ['Aus epithelialem Gewebe', 'Aus mesenchymalem Gewebe', 'Nur aus Nervenzellen'],
  'correct': 0,
  'explanation': 'Karzinome entstehen aus epithelialem Gewebe; Sarkome aus mesenchymalem Gewebe.',
  'variants': ['maze_portals', 'pokemon_battle']},
 {'id': 'aflatoxin_dna',
  'page': 7,
  'question': 'Was passiert nach metabolischer Aktivierung von Aflatoxin B1?',
  'answers': ['Ein reaktives Epoxid kann an DNA binden', 'Es wird immer direkt ausgeschieden', 'Es bindet nur reversibel an Hämoglobin'],
  'correct': 0,
  'explanation': 'Aflatoxin B1 kann durch CYP450 zu einem reaktiven Epoxid werden, das an DNA bindet und Mutationen verursachen kann.',
  'variants': ['comet_click', 'pokemon_battle']}]
