"""Questions from the provided toxicology notes."""

FOUNDATIONS_QUESTIONS = [{'id': 'toxicokinetics_definition',
  'page': 1,
  'question': 'Was beschreibt die Toxikokinetik?',
  'answers': ['Was der Körper mit dem Fremdstoff macht', 'Was der Fremdstoff mit dem Körper macht', 'Nur die Ausscheidung'],
  'correct': 0,
  'explanation': 'Toxikokinetik beschreibt, was der Körper mit einem Fremdstoff macht.',
  'variants': ['sole_man', 'maze_portals']},
 {'id': 'toxicodynamics_definition',
  'page': 1,
  'question': 'Was beschreibt die Toxikodynamik?',
  'answers': ['Was der Fremdstoff mit dem Körper macht', 'Nur die Resorption', 'Was der Körper mit dem Fremdstoff macht'],
  'correct': 0,
  'explanation': 'Toxikodynamik beschreibt die Wirkung des Fremdstoffs auf den Körper bzw. seinen Wirkmechanismus.',
  'variants': ['platform_gates', 'sole_man']},
 {'id': 'ladme_absorption',
  'page': 1,
  'question': 'Wofür steht die Absorption im LADME-Schema?',
  'answers': ['Resorption und Aufnahme ins Blut', 'Freisetzung aus der Tablette', 'Ausscheidung über die Niere'],
  'correct': 0,
  'explanation': 'Absorption bedeutet Resorption bzw. Aufnahme in das Blut.',
  'variants': ['lab_catcher', 'sword_arena']},
 {'id': 'resorption_small_intestine',
  'page': 1,
  'question': 'Wo findet laut Notizen der Großteil der Resorption statt?',
  'answers': ['Im Dünndarm', 'In der Leber', 'In der Lunge'],
  'correct': 0,
  'explanation': 'Der Großteil der Resorption findet im Dünndarm statt.',
  'variants': ['maze_portals', 'platform_gates']},
 {'id': 'first_pass',
  'page': 1,
  'question': 'Was ist der First-Pass-Effekt?',
  'answers': ['Umwandlung eines Stoffes bei der ersten Leberpassage', 'Ausscheidung über die Lunge', 'Bindung eines Stoffes an DNA'],
  'correct': 0,
  'explanation': 'Beim First-Pass-Effekt wird ein Stoff während seiner ersten Passage durch die Leber umgewandelt.',
  'variants': ['sole_man', 'lab_catcher']},
 {'id': 'first_pass_bioavailability',
  'page': 2,
  'question': 'Was bewirkt ein stark ausgeprägter First-Pass-Effekt?',
  'answers': ['Geringere Bioverfügbarkeit', 'Höhere Bioverfügbarkeit', 'Keine Metabolisierung'],
  'correct': 0,
  'explanation': 'Starke Metabolisierung in Leber und ggf. Enterozyten lässt weniger Wirkstoff in den Blutkreislauf gelangen.',
  'variants': ['sword_arena', 'sole_man']},
 {'id': 'phase1_reactions',
  'page': 2,
  'question': 'Welche Reaktion gehört zur Phase I des Fremdstoffmetabolismus?',
  'answers': ['Oxidation', 'Glucuronidierung', 'Glutathion-Konjugation'],
  'correct': 0,
  'explanation': 'Phase I umfasst z. B. Oxidation, Reduktion, Hydrolyse und Desaminierung.',
  'variants': ['lab_catcher', 'sole_man']},
 {'id': 'phase2_goal',
  'page': 2,
  'question': 'Was ist das typische Ziel von Phase II?',
  'answers': ['Stoffe wasserlöslicher für die Ausscheidung machen', 'Stoffe immer giftiger machen', 'Stoffe in den Zellkern transportieren'],
  'correct': 0,
  'explanation': 'In Phase II werden Stoffe mit wasserlöslichen Gruppen verbunden; die Produkte können dann z. B. über die Niere ausgeschieden werden.',
  'variants': ['platform_gates', 'comet_click']},
 {'id': 'metabolite_definition',
  'page': 2,
  'question': 'Was ist ein Metabolit?',
  'answers': ['Produkt nach der Umwandlung eines Stoffes', 'Nur ein unveränderter Ausgangsstoff', 'Ein Ausscheidungsorgan'],
  'correct': 0,
  'explanation': 'Ein Metabolit ist das Produkt, das nach der Umwandlung eines Stoffes entsteht; es kann weniger, gleich oder stärker giftig sein.',
  'variants': ['sword_arena', 'comet_click']},
 {'id': 'aflatoxin_activation',
  'page': 2,
  'question': 'Was kann bei Phase I mit Aflatoxin passieren?',
  'answers': ['Aktivierung zu einem reaktiven Epoxid', 'Immer vollständige Entgiftung', 'Direkte Ausscheidung ohne Umwandlung'],
  'correct': 0,
  'explanation': 'Die Notizen warnen davor, dass Phase I krebserregende Stoffe aktivieren kann, z. B. Aflatoxin zu einem Epoxid.',
  'variants': ['maze_portals', 'lab_catcher']},
 {'id': 'alcohol_adh',
  'page': 3,
  'question': 'Welches Enzym wandelt Ethanol zu Acetaldehyd um?',
  'answers': ['ADH', 'ALDH', 'CYP3A4'],
  'correct': 0,
  'explanation': 'ADH (Alkoholdehydrogenase) wandelt Ethanol zu Acetaldehyd um.',
  'variants': ['sole_man', 'sword_arena']},
 {'id': 'alcohol_aldh',
  'page': 3,
  'question': 'Welches Enzym wandelt Acetaldehyd zu Acetat um?',
  'answers': ['ALDH', 'ADH', 'CYP450'],
  'correct': 0,
  'explanation': 'ALDH (Aldehyddehydrogenase) wandelt Acetaldehyd zu Acetat um.',
  'variants': ['comet_click', 'maze_portals']},
 {'id': 'flushing_syndrome',
  'page': 3,
  'question': 'Warum sammelt sich beim Flushing-Syndrom Acetaldehyd an?',
  'answers': ['ALDH arbeitet langsamer oder kaum', 'ADH fehlt immer vollständig', 'Die Niere resorbiert Acetaldehyd'],
  'correct': 0,
  'explanation': 'Bei langsam oder kaum arbeitender ALDH kann Acetaldehyd im Körper akkumulieren.',
  'variants': ['lab_catcher', 'sole_man']},
 {'id': 'enzyme_inducers',
  'page': 3,
  'question': 'Was können Enzyminduktoren laut Notizen aktivieren?',
  'answers': ['Cytochrom-P450-Monooxygenasen', 'Nur Nierenfiltration', 'Nur Antikörper'],
  'correct': 0,
  'explanation': 'Enzyminduktoren können CYP450-Monooxygenasen aktivieren und damit Metabolisierung beschleunigen oder mehr toxische Metabolite erzeugen.',
  'variants': ['sword_arena', 'maze_portals']},
 {'id': 'grapefruit_cyp3a4',
  'page': 3,
  'question': 'Welche Wirkung hat Grapefruitsaft laut Notizen auf CYP3A4?',
  'answers': ['Er hemmt CYP3A4 vor allem im Enterozyten', 'Er induziert CYP3A4 stark', 'Er zerstört Hämoglobin'],
  'correct': 0,
  'explanation': 'Grapefruitsaft hemmt CYP3A4 vor allem in Darmzellen; dadurch kann die Wirkung mancher Arzneistoffe verstärkt oder verlängert werden.',
  'variants': ['comet_click', 'lab_catcher']},
 {'id': 'organotropism',
  'page': 4,
  'question': 'Was bedeutet Organotropie?',
  'answers': ['Ein toxischer Stoff verteilt sich bevorzugt an bestimmte Organe', 'Alle Stoffe verteilen sich immer gleich', 'Nur die Ausscheidung über Haare'],
  'correct': 0,
  'explanation': 'Organotropie bedeutet eine bevorzugte Verteilung eines toxischen Stoffes an bestimmte Organe.',
  'variants': ['maze_portals', 'sole_man']}]
