"""Questions from the provided toxicology notes."""

RISK_QUESTIONS = [{'id': 'hazard_risk',
  'page': 15,
  'question': 'Was unterscheidet Gefahr (Hazard) und Risiko?',
  'answers': ['Risiko berücksichtigt zusätzlich die tatsächliche Exposition', 'Gefahr berücksichtigt immer die Expositionshäufigkeit', 'Beides bedeutet exakt dasselbe'],
  'correct': 0,
  'explanation': 'Gefahr ist die grundsätzliche Fähigkeit, Schaden zu verursachen. Risiko berücksichtigt die konkrete Exposition: wie viel, wie häufig und wie lange.',
  'variants': ['platform_gates', 'quick_draw']},
 {'id': 'risk_assessment_steps',
  'page': 15,
  'question': 'Welche Reihenfolge passt zur Risikobewertung in den Notizen?',
  'answers': ['Gefahr feststellen -> Gefahr charakterisieren -> Exposition abschätzen -> Risiko charakterisieren', 'Exposition -> Ausscheidung -> Mutation -> Resorption', 'ADI -> TDI -> MRL -> BMD'],
  'correct': 0,
  'explanation': 'Die vier Schritte sind Gefahrenidentifikation, Gefahrencharakterisierung, Expositionsabschätzung und Risikobestimmung/-charakterisierung.',
  'variants': ['comet_click', 'sword_arena']},
 {'id': 'threshold_exceptions',
  'page': 17,
  'question': 'Für welche Gruppen nennen die Notizen keine Wirkschwelle?',
  'answers': ['Genotoxische Kanzerogene und Allergene', 'Alle Konzentrationsgifte', 'Alle Phase-II-Metabolite'],
  'correct': 0,
  'explanation': 'Auf Seite 17 steht: Für genotoxische Kanzerogene und Allergene gibt es keine Wirkschwelle.',
  'variants': ['quick_draw', 'platform_gates']},
 {'id': 'concentration_vs_summation',
  'page': 18,
  'question': 'Was kennzeichnet ein Summationsgift?',
  'answers': ['Schäden können sich über die Zeit summieren', 'Wirkung hängt nur von der aktuellen Konzentration ab', 'Die Wirkung ist immer sofort reversibel'],
  'correct': 0,
  'explanation': 'Bei Summationsgiften kann die entstandene Schädigung bleiben und sich bei erneuter Exposition weiter summieren; chemische Kanzerogene werden als Beispiel genannt.',
  'variants': ['sword_arena', 'maze_portals']},
 {'id': 'noael_loael_curve',
  'page': 19,
  'question': 'Bei 0, 5, 20, 50 und 100 mg/kg tritt erstmals bei 50 mg/kg eine Leberschädigung auf. Was gilt?',
  'answers': ['NOAEL 20 mg/kg, LOAEL 50 mg/kg', 'NOAEL 50 mg/kg, LOAEL 20 mg/kg', 'NOAEL 100 mg/kg, LOAEL 0 mg/kg'],
  'correct': 0,
  'explanation': 'Die höchste getestete Dosis ohne schädliche Wirkung ist 20 mg/kg; die niedrigste mit schädlicher Wirkung ist 50 mg/kg.',
  'variants': ['comet_click', 'quick_draw']},
 {'id': 'adi_tdi',
  'page': 20,
  'question': 'Was ist der typische Unterschied zwischen ADI und TDI?',
  'answers': ['ADI eher absichtlich eingesetzter Stoff; TDI eher unerwünschter Kontaminant', 'ADI gilt nur einmalig; TDI nur für 14 Tage', 'TDI ist immer höher als ADI'],
  'correct': 0,
  'explanation': 'ADI wird typischerweise für absichtlich eingesetzte/zugelassene Stoffe verwendet, TDI für unerwünschte Kontaminanten.',
  'variants': ['maze_portals', 'platform_gates']},
 {'id': 'adi_calculation',
  'page': 20,
  'question': 'Wie wird der ADI laut Notizen typischerweise abgeleitet?',
  'answers': ['NOEL oder NOAEL geteilt durch Sicherheitsfaktor', 'LOAEL mal Körpergewicht', 'BMDL plus Exposition'],
  'correct': 0,
  'explanation': 'ADI = NOEL oder NOAEL / Sicherheitsfaktor. Häufig wird ein Faktor 100 verwendet (10 x 10).',
  'variants': ['platform_gates', 'sword_arena']},
 {'id': 'adi_once',
  'page': 21,
  'question': 'Bedeutet eine einmalige kleine ADI-Überschreitung automatisch eine sofortige Vergiftung?',
  'answers': ['Nein', 'Ja, immer', 'Nur wenn der Stoff wasserlöslich ist'],
  'correct': 0,
  'explanation': 'Der ADI ist auf tägliche lebenslange Aufnahme ausgelegt und enthält Sicherheitsfaktoren; problematisch ist vor allem eine regelmäßige bzw. dauerhafte Überschreitung.',
  'variants': ['quick_draw', 'comet_click']},
 {'id': 'arfd',
  'page': 21,
  'question': 'Worauf bezieht sich die ARfD?',
  'answers': ['Akutes Risiko bei Aufnahme innerhalb einer Mahlzeit oder eines Tages', 'Lebenslange tägliche Aufnahme', 'Nur Arbeitsplatzexposition'],
  'correct': 0,
  'explanation': 'ARfD steht für akute Referenzdosis und bezieht sich auf eine Aufnahme innerhalb einer Mahlzeit oder eines Tages ohne erwartetes akutes Risiko.',
  'variants': ['sword_arena', 'maze_portals']},
 {'id': 'bmd_bmdl',
  'page': 22,
  'question': 'Was ist die BMDL?',
  'answers': ['Untere, vorsichtigere Grenze des Vertrauensbereichs der Benchmark-Dosis', 'Die höchste gemessene Wirkung', 'Ein Arbeitsplatzgrenzwert'],
  'correct': 0,
  'explanation': 'BMDL ist die untere statistisch abgesicherte bzw. vorsichtigere Grenze des Vertrauensbereichs der Benchmark-Dosis.',
  'variants': ['comet_click', 'quick_draw']},
 {'id': 'moe',
  'page': 23,
  'question': 'Was bedeutet ein hoher Margin of Exposure (MoE) laut Notizen?',
  'answers': ['Großer Abstand zur problematischen Dosis und damit geringeres Gesundheitsrisiko', 'Höheres Risiko durch größere Exposition', 'Sichere Mutation'],
  'correct': 0,
  'explanation': 'Der MoE ist der Abstand zwischen einer kanzerogenen Dosis ohne erkennbare Wirkung (BMDL10) und der menschlichen Exposition. Ein hoher Abstand spricht für geringeres Risiko.',
  'variants': ['maze_portals', 'lab_catcher']}]
