"""Questions from the provided toxicology notes."""

TESTS_QUESTIONS = [{'id': 'eas_definition',
  'page': 8,
  'question': 'Was sind endokrin aktive Substanzen (EAS)?',
  'answers': ['Stoffe, die normale Hormonaktivität beeinflussen oder stören können', 'Nur Stoffe, die DNA schneiden', 'Nur Nierengifte'],
  'correct': 0,
  'explanation': 'EAS können normale Hormonaktivität beeinflussen oder stören, z. B. senken, ändern, nachahmen oder beschleunigen.',
  'variants': ['lab_catcher', 'maze_portals']},
 {'id': 'endocrine_disruptor_conditions',
  'page': 8,
  'question': 'Welche Bedingung gehört zur Definition eines endokrinen Disruptors?',
  'answers': ['Es liegt eine schädliche Wirkung vor', 'Es darf keine endokrine Aktivität geben', 'Ein ursächlicher Zusammenhang ist ausgeschlossen'],
  'correct': 0,
  'explanation': 'Die Notizen nennen drei Bedingungen: schädliche Wirkung, endokrine Aktivität und ein plausibler ursächlicher Zusammenhang zwischen beiden.',
  'variants': ['platform_gates', 'comet_click']},
 {'id': 'zearalenone',
  'page': 8,
  'question': 'Welche Wirkung wird Zearalenon in den Notizen zugeordnet?',
  'answers': ['Östrogene Wirkung als Xenoöstrogen', 'CYP3A4-Hemmung', 'Primäre DNA-Schäden im Comet-Assay'],
  'correct': 0,
  'explanation': 'Zearalenon wird als Mykotoxin mit östrogener Wirkung bzw. Xenoöstrogen genannt.',
  'variants': ['sword_arena', 'lab_catcher']},
 {'id': 'ames_detects',
  'page': 8,
  'question': 'Was prüft der Ames-Test?',
  'answers': ['Mutagenität', 'Akute Toxizität', 'Nur Lebergewicht'],
  'correct': 0,
  'explanation': 'Der Ames-Test ist ein bakterieller Reversionstest auf mutagene Wirkung.',
  'variants': ['maze_portals', 'comet_click']},
 {'id': 'ames_bacteria',
  'page': 8,
  'question': 'Welches Bakterium wird in den Notizen typisch für den Ames-Test genannt?',
  'answers': ['Salmonella typhimurium', 'Staphylococcus aureus', 'Bacillus subtilis'],
  'correct': 0,
  'explanation': 'Als typischer Testorganismus wird Salmonella typhimurium genannt; die Stämme benötigen Histidin.',
  'variants': ['platform_gates', 'sword_arena']},
 {'id': 's9_mix',
  'page': 9,
  'question': 'Wozu dient der S9-Mix im Ames-Test?',
  'answers': ['Er simuliert metabolische Aktivierung durch die Leber', 'Er färbt DNA-Fragmente', 'Er ersetzt die Bakterien'],
  'correct': 0,
  'explanation': 'Der S9-Mix aus Leberextrakt simuliert die metabolische Aktivierung durch die Leber.',
  'variants': ['lab_catcher', 'maze_portals']},
 {'id': 'ames_s9_positive',
  'page': 9,
  'question': 'Was deutet ein Ames-Test an, der nur mit S9-Mix positiv ist?',
  'answers': ['Auf ein Promutagen, das metabolisch aktiviert werden muss', 'Auf einen Stoff ohne mutagene Wirkung', 'Auf reine akute Toxizität'],
  'correct': 0,
  'explanation': 'Nur mit S9 positiv spricht laut Notizen für ein Promutagen bzw. indirekt wirkendes Mutagen, das erst metabolisch aktiviert wird.',
  'variants': ['comet_click', 'platform_gates']},
 {'id': 'comet_assay',
  'page': 10,
  'question': 'Was weist der Comet-Assay nach?',
  'answers': ['Primäre DNA-Schäden', 'Nur Mutationen in Bakterien', 'Nur endokrine Aktivität'],
  'correct': 0,
  'explanation': 'Der Comet-Assay (Single Cell Gel Electrophoresis) weist primäre DNA-Schäden in einzelnen, meist eukaryotischen Zellen nach.',
  'variants': ['sword_arena', 'comet_click']},
 {'id': 'comet_tail',
  'page': 10,
  'question': "Warum entsteht bei geschädigter DNA im Comet-Assay ein 'Schweif'?",
  'answers': ['DNA-Fragmente wandern weiter aus dem Zellkern', 'Gesunde DNA löst sich vollständig auf', 'Bakterien bilden Kolonien'],
  'correct': 0,
  'explanation': 'Kleinere bzw. lockere DNA-Fragmente können im elektrischen Feld weiter aus dem Zellkern wandern und erzeugen den charakteristischen Schweif.',
  'variants': ['maze_portals', 'lab_catcher']},
 {'id': 'ames_vs_comet',
  'page': 11,
  'question': 'Welcher Merksatz unterscheidet Ames-Test und Comet-Assay?',
  'answers': ['Ames = Mutation, Comet = DNA-Schädigung', 'Ames = DNA-Schweif, Comet = Kolonien', 'Beide prüfen nur akute Toxizität'],
  'correct': 0,
  'explanation': 'Der Merksatz auf Seite 11 lautet sinngemäß: Ames prüft Mutation/Mutagenität, Comet betrachtet DNA-Schädigung.',
  'variants': ['platform_gates', 'sword_arena']},
 {'id': 'three_r',
  'page': 12,
  'question': 'Wofür stehen die 3R bei Tierversuchen?',
  'answers': ['Refine, Reduce, Replace', 'Repeat, React, Repair', 'Risk, Response, Recovery'],
  'correct': 0,
  'explanation': '3R: Refine = Belastung verringern, Reduce = Tierzahl reduzieren, Replace = Tierversuche möglichst ersetzen.',
  'variants': ['comet_click', 'maze_portals']},
 {'id': 'toxicity_duration',
  'page': 12,
  'question': 'Welche Dauer ist in den Notizen der subchronischen Toxizität zugeordnet?',
  'answers': ['90 Tage', '14 Tage', '28 Tage'],
  'correct': 0,
  'explanation': 'Die Notizen ordnen akut ca. 14 Tage, subakut ca. 28 Tage und subchronisch 90 Tage zu.',
  'variants': ['lab_catcher', 'platform_gates']},
 {'id': 'noel_noael',
  'page': 13,
  'question': 'Was unterscheidet NOEL und NOAEL?',
  'answers': ['NOEL: keine Wirkung; NOAEL: keine schädliche Wirkung', 'NOEL ist immer größer als LOAEL', 'NOAEL bedeutet erste schädliche Wirkung'],
  'correct': 0,
  'explanation': 'NOEL ist die höchste untersuchte Dosis ohne beobachtbare Wirkung; NOAEL die höchste Dosis ohne schädliche Wirkung.',
  'variants': ['sword_arena', 'comet_click']},
 {'id': 'loael',
  'page': 13,
  'question': 'Was ist der LOAEL?',
  'answers': ['Niedrigste untersuchte Dosis mit schädlicher Wirkung', 'Höchste Dosis ohne jegliche Wirkung', 'Zulässige Rückstandskonzentration im Lebensmittel'],
  'correct': 0,
  'explanation': 'LOAEL = niedrigste untersuchte Dosis, bei der eine schädliche Wirkung beobachtet wurde.',
  'variants': ['maze_portals', 'lab_catcher']}]
